name = "Github project Page"
license = "MIT"
licenselink = "https://github.com/nsomar/github-project-landing-page/blob/master/LICENSE.md"
description = "An easy to use landing page theme for github hosted project."
min_version= 0.1

[author]
     name = "Daniel Gomez"

[original]
    author =  "Omar Abdelhafith"
    homepage = "https://github.com/nsomar/github-project-landing-page"
    repo = "https://github.com/nsomar/github-project-landing-page"

